## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [19]:
import pandas as pd

In [20]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [25]:
male_rows = data[data["sex"] == "Male"]
female_rows = data[data["sex"] == "Female"]

print(len(male_rows))
print(len(female_rows))

10771

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [26]:
avg_male_age = data["age"].mean()
avg_male_age

np.float64(38.58164675532078)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [31]:
# usa_people_rows = data[data["native-country"] == "United-States"]
# usa_people_percentage = len(usa_people_rows) / len(data) * 100

usa_percentage = data["native-country"].value_counts(normalize=True)
usa_percentage = usa_percentage["United-States"] * 100
usa_percentage

np.float64(89.5857006848684)

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [45]:
less_than_50k_ages = data[data["salary"] == "<=50K"]["age"]
more_than_50k_ages = data[data["salary"] == ">50K"]["age"]

print(
f'''Mean Age:
    Salary more than 50k: {more_than_50k_ages.mean()}
    Salary less than 50k: {less_than_50k_ages.mean()}
Age Stds:
    Salary more than 50k: {more_than_50k_ages.std()}
    Salary less than 50k: {less_than_50k_ages.std()}''')

Mean Age:
    Salary more than 50k: 44.24984058155847
    Salary less than 50k: 36.78373786407767
Age Stds:
    Salary more than 50k: 10.51902771985177
    Salary less than 50k: 14.020088490824813

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [56]:
more_than_50k_education = data[data["salary"] == ">50K"]["education"]
more_than_50k_education = more_than_50k_education.value_counts(normalize=True)
percentage_of_education = more_than_50k_education[["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters", "Doctorate"]].sum() * 100
print(f'Only {round(percentage_of_education, 2)}% of rich people have higher education')

Only 57.84% of rich people have higher education

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [62]:
age_stats = data.groupby(["race", "sex"])["age"].describe()
max_age = age_stats.loc[('Asian-Pac-Islander', 'Male'), 'max']
max_age

np.float64(90.0)

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [85]:
rich_men_marital_statuses = data[(data['sex'] == 'Male') & (data['salary'] == '>50K')]['marital-status']
married_rich = rich_men_marital_statuses.value_counts(normalize=True)[['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']].sum()
married_rich_percentage = round(married_rich* 100, 2)
print(f'''Married percentage: {married_rich_percentage}%
Not married percentage: {round(100 - married_rich_percentage, 2)}%''')

Married percentage: 89.54%
Not married percentage: 10.46%

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [93]:
max_hours = data['hours-per-week'].max()
hardworking_people = data[data['hours-per-week'] == max_hours]
hardworking_rich_people = hardworking_people[hardworking_people['salary'] == '>50K']
print(f'''Number of people who work {max_hours} a week: {len(hardworking_people)}
Number of these people who are rich: {len(hardworking_rich_people)}
Percentage of rich {round(len(hardworking_rich_people)/len(hardworking_people) * 100, 2)}%''')

Number of people who work 99 a week: 85
Number of these people who are rich: 25
Percentage of rich 29.41%

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [94]:
result = data.groupby(['native-country', 'salary'])['hours-per-week'].mean()
result

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [97]:
data['AgeGroup'] = pd.cut(data['age'], bins=[16, 35, 70, 100], labels=['young', 'adult', 'retiree'])
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,young
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,adult
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,adult
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,young
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,adult

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [106]:
rich_groups = data[data['salary'] == '>50K']['AgeGroup'].value_counts()
print(f'Most common to be rich is "{rich_groups.idxmax()}" group')

Most common to be rich is "adult" group

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [115]:
def group_filter_func(rows):
  return rows['age'].mean() <= 40 and (rows['hours-per-week'] > 5).all()

result = data.groupby(['occupation']).filter(group_filter_func)
print(result['occupation'].unique())

['Armed-Forces']